# Generated by Django 3.1.2 on 2020-10-31 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'role',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('u_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('u_password', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=128, unique=True)),
                ('u_total_amount', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('projects_supported', models.IntegerField(blank=True, null=True)),
                ('role', models.ForeignKey(blank=True, db_column='role', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crowdfunding.role')),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=264)),
                ('description', models.CharField(max_length=1200)),
                ('p_location', models.CharField(blank=True, max_length=264, null=True)),
                ('category', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('goal', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('current_amount', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('userid', models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crowdfunding.users')),
            ],
            options={
                'db_table': 'project',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('p', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crowdfunding.project')),
                ('userid', models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crowdfunding.users')),
            ],
            options={
                'db_table': 'fund',
                'managed': True,
            },
        ),
    ]
